-- ============================================================================
-- SAM Demo - Teardown Script
-- ============================================================================
-- This script removes all SAM demo components from your Snowflake account.
--
-- WARNING: This will permanently delete all data and AI components!
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- Remove Cortex Agents (must be done before dropping database)
DROP AGENT IF EXISTS SAM_DEMO.AI.portfolio_copilot;
DROP AGENT IF EXISTS SAM_DEMO.AI.research_copilot;
DROP AGENT IF EXISTS SAM_DEMO.AI.thematic_macro_advisor;
DROP AGENT IF EXISTS SAM_DEMO.AI.esg_guardian;
DROP AGENT IF EXISTS SAM_DEMO.AI.sales_advisor;
DROP AGENT IF EXISTS SAM_DEMO.AI.quant_analyst;
DROP AGENT IF EXISTS SAM_DEMO.AI.compliance_advisor;
DROP AGENT IF EXISTS SAM_DEMO.AI.middle_office_copilot;
DROP AGENT IF EXISTS SAM_DEMO.AI.executive_copilot;

-- Drop Cortex Search Services
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_BROKER_RESEARCH;
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_COMPANY_EVENTS;
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_PRESS_RELEASES;
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_NGO_REPORTS;
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_ENGAGEMENT_NOTES;
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_POLICY_DOCS;
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_SALES_TEMPLATES;
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_PHILOSOPHY_DOCS;
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_REPORT_TEMPLATES;
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_MACRO_EVENTS;
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_CUSTODIAN_REPORTS;
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_RECONCILIATION_NOTES;
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_SSI_DOCUMENTS;
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_OPS_PROCEDURES;
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_STRATEGY_DOCUMENTS;
DROP CORTEX SEARCH SERVICE IF EXISTS SAM_DEMO.AI.SAM_REAL_SEC_FILINGS;

-- Drop Semantic Views
DROP SEMANTIC VIEW IF EXISTS SAM_DEMO.AI.SAM_ANALYST_VIEW;
DROP SEMANTIC VIEW IF EXISTS SAM_DEMO.AI.SAM_FUNDAMENTALS_VIEW;
DROP SEMANTIC VIEW IF EXISTS SAM_DEMO.AI.SAM_STOCK_PRICES_VIEW;
DROP SEMANTIC VIEW IF EXISTS SAM_DEMO.AI.SAM_ESG_VIEW;
DROP SEMANTIC VIEW IF EXISTS SAM_DEMO.AI.SAM_THEMATIC_VIEW;
DROP SEMANTIC VIEW IF EXISTS SAM_DEMO.AI.SAM_SALES_VIEW;
DROP SEMANTIC VIEW IF EXISTS SAM_DEMO.AI.SAM_COMPLIANCE_VIEW;
DROP SEMANTIC VIEW IF EXISTS SAM_DEMO.AI.SAM_SUPPLY_CHAIN_VIEW;
DROP SEMANTIC VIEW IF EXISTS SAM_DEMO.AI.SAM_MIDDLE_OFFICE_VIEW;
DROP SEMANTIC VIEW IF EXISTS SAM_DEMO.AI.SAM_EXECUTIVE_VIEW;

-- Remove Git Integration (must be done before dropping database)
DROP GIT REPOSITORY IF EXISTS SAM_DEMO.PUBLIC.sam_demo_repo;
DROP SECRET IF EXISTS SAM_DEMO.PUBLIC.GITHUB_SECRET;
DROP API INTEGRATION IF EXISTS GITHUB_INTEGRATION_SAM_DEMO;

-- Drop Database (includes all tables, views, procedures, stages)
DROP DATABASE IF EXISTS SAM_DEMO CASCADE;

-- Drop Warehouse
DROP WAREHOUSE IF EXISTS SAM_DEMO_WH;

-- Drop Role
REVOKE ROLE SAM_DEMO_ROLE FROM ROLE ACCOUNTADMIN;
REVOKE ROLE SAM_DEMO_ROLE FROM ROLE SYSADMIN;
DROP ROLE IF EXISTS SAM_DEMO_ROLE;

-- Completion message
SELECT 'Teardown complete - all SAM demo components removed' AS status;

